export const POST_NEW_PRODUCT = "POST_NEW_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
export const UPDATE_PRODUCT_BY_ID = "UPDATE_PRODUCT_BY_ID";
export const POST_NEW_VENTA = "POST_NEW_VENTA";
export const GET_ALL_VENTAS = "GET_ALL_VENTAS";
export const GET_VENTA_BY_ID = "GET_VENTA_BY_ID";
export const DELETE_VENTA_BY_ID = "DELETE_VENTA_BY_ID";
export const UPDATE_VENTA_BY_ID = "UPDATE_VENTA_BY_ID";
export const POST_NEW_USER = "POST_NEW_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";



